### ISSUE TITLE
Incorporar ensamblador de ORGA1 de Lartu

### ISSUE THREAD

**Issue by dgarroDC** [rozen03/dcubabot#3]
https://github.com/Lartu/orga1bot

Dale @Lartu

**Comment by Lartu** [comment]
No lo agrego una mierda ahora porque rozen es un BOBO :sleepy:

**Comment by iglosiggio** [comment]
El ensamblador de tu repo está completo? @Lartu

**Comment by Lartu** [comment]
Sip

**Comment by rozen03** [comment]
Bueno, si nadie lo hace lo cierro

**Comment by Lartu** [comment]
Qué no habían cerrado este antro? (?
