### ISSUE TITLE
Hacer un /listarlabos

### ISSUE THREAD

**Issue by iglosiggio** [rozen03/dcubabot#8]
Se podría usar alguna biblioteca para parsear ICS y tener alguna tarea que resincronize los calendarios cada hora (aprox).

Dejo (a modo de documentación) los links de los calendarios y el de una posible biblioteca:

* **Labo 1:** https://calendar.google.com/calendar/ical/s57pjfhll16pqpu456eonvb760%40group.calendar.google.com/public/basic.ics
* **Labo 2:** https://calendar.google.com/calendar/ical/bupjqrv2va0nb3bv3o1f1jqtc0%40group.calendar.google.com/public/basic.ics
* **Labo 3 (Graduados):** https://calendar.google.com/calendar/ical/n3sd0tpdt0o5855evq8uvsi3vo%40group.calendar.google.com/public/basic.ics
* **Labo 4:** https://calendar.google.com/calendar/ical/4lbn08p17sv8s2pfqoophliag4%40group.calendar.google.com/public/basic.ics
* **Labo 5:** https://calendar.google.com/calendar/ical/fu35kvoh4i2looi4drjf17k1ts%40group.calendar.google.com/public/basic.ics
* **Labo 6:** https://calendar.google.com/calendar/ical/g3jdt9mmsrqllp7hqfotvttsck%40group.calendar.google.com/public/basic.ics
* **Labo 7 (Turing):** https://calendar.google.com/calendar/ical/krs8uvil4o36kd3a3ad5qs57dg%40group.calendar.google.com/public/basic.ics
* **ics:** https://github.com/C4ptainCrunch/ics.py

**Comment by iglosiggio** [comment]
Armé un [archivito de prueba](https://github.com/iglosiggio/dcubabot/blob/master/labos.py) que recarga cuando le hacen una consulta y considera los calendarios “vencidos”. Lo único feo es que agregué `pytz` como dependencia por el tema de las timezones.

Un ejemplo de cómo usar el archivito:
```py
import labos
from datetime import timedelta

time = labos.aware_now() - timedelta(days=1, hours=10)

for event in labos.events_at(time):
    print(event)
```

**Comment by dgarroDC** [comment]
La lib para parsear los calendarios no tiene soporte para eventos que se repiten: C4ptainCrunch/ics.py#14  :(
